// MyLabel.h — generated by the PaperCanvas layout tool.
//   https://tanakamasayuki.github.io/PaperCanvas/
//
// Fill in the data struct and call the build function. Regenerating this
// file overwrites it, so keep your own code elsewhere.
//
// Label, 400 x 240 dots.

#pragma once

#include <PaperCanvas.h>

using PaperCanvas::Align;
using PaperCanvas::Rect;
using PaperCanvas::VAlign;

/// Everything the layout needs from the caller.
struct MyLabelData {
  const char* title;
  const char* itemName;
  const char* weight;
  const char* price;
  const char* bestBefore;
};

inline void buildMyLabel(PaperCanvas::Label& lb, const MyLabelData& d) {
  lb.setFont(&fonts::lgfxJapanGothic_16);

  lb.addRect(Rect{0, 0, 400, 240}, false, 2);
  lb.addText(Rect{12, 12, 376, 24}, d.title, {.align = Align::Center});
  lb.addRow(Rect{12, 44, 376, 20}, d.itemName, d.weight, d.price);
  lb.addLine(12, 170, 387, 170, 1);
  lb.addText(Rect{12, 182, 376, 24}, d.bestBefore);
}

/* Usage:

  MyLabelData d = {"産地直送", "トマト", "1kg", "580", "2026-09-01"};

  PaperCanvas::Label lb(400, 240);
  buildMyLabel(lb, d);

  static uint8_t page[PaperCanvas::rowBytes(400) * 240];
  if (lb.build(page, sizeof(page))) {
    sendToPrinter(page, lb.width(), lb.height());   // your driver
  }
*/