// MyReceipt.h — generated by the PaperCanvas layout tool.
//   https://tanakamasayuki.github.io/PaperCanvas/
//
// Fill in the data struct and call the build function. Regenerating this
// file overwrites it, so keep your own code elsewhere.
//
// Receipt, 384 dots wide.

#pragma once

#include <PaperCanvas.h>

using PaperCanvas::Align;
using PaperCanvas::Column;

/// One line of the table. The caller passes an array of these.
struct MyReceiptItem {
  const char* name;
  const char* qty;
  const char* price;
};

/// Everything the layout needs from the caller.
struct MyReceiptData {
  const char* shopName;
  const char* datetime;
  const char* total;
  const MyReceiptItem* items;
  size_t itemCount;
};

/// Build the receipt. Call r.build() or r.stream() afterwards.
inline void buildMyReceipt(PaperCanvas::Receipt& r, const MyReceiptData& d) {
  r.setFont(&fonts::lgfxJapanGothic_16);
  r.setMargin(8, 16, 4, 4);
  r.setWrap(true);

  r.setAlign(Align::Center);
  r.addText(d.shopName, {.align = Align::Center});
  r.addText(d.datetime, {.align = Align::Center});
  r.addSpace(6);
  r.addRule('-');

  // Table: one row per item, however many the caller passes.
  static const Column columns[] = {
      Column::rest(Align::Left),
      Column::autoFit(Align::Center),
      Column::autoFit(Align::Right),
  };
  r.setColumns(columns, 3);
  r.setColumnGap(8);
  r.addRow("品名", "数量", "金額");
  r.addLine(1);
  for (size_t i = 0; i < d.itemCount; ++i) {
    const MyReceiptItem& it = d.items[i];
    r.addRow(it.name, it.qty, it.price);
  }
  r.addLine(1);
  r.clearColumns();

  r.addRow("合計", d.total);
  r.addSpace(8);
  r.addText("ご来店ありがとうございます", {.align = Align::Center});
}

/* Usage:

  MyReceiptItem items[] = {
      {"コーヒー", "x2", "960"},
      {"サンドイッチ", "x1", "620"},
  };
  MyReceiptData d = {"PaperCanvas Cafe", "2026-08-17 14:32", "1580", items, sizeof(items) / sizeof(items[0])};

  PaperCanvas::Receipt r(384);
  buildMyReceipt(r, d);

  static uint8_t page[PaperCanvas::rowBytes(384) * 800];
  if (r.build(page, sizeof(page))) {
    sendToPrinter(page, r.width(), r.height());   // your driver
  }
*/