/* Auto-generated by tools/bump_version.py - do not edit manually */
#ifndef PAPERCANVAS_VERSION_H
#define PAPERCANVAS_VERSION_H

#define PAPERCANVAS_VERSION_MAJOR 0
#define PAPERCANVAS_VERSION_MINOR 0
#define PAPERCANVAS_VERSION_PATCH 0
#define PAPERCANVAS_VERSION_STR "0.0.0"

#endif // PAPERCANVAS_VERSION_H
